language: node_js
node_js:
  - 12
os:
  - linux
  - osx
  - windows
# This (filter_secrets) is generally unsafe, but we only run builds for master,
# so it is acceptable. If we remove the branch restriction, remove this too.
# If Windows builds on Travis are fixed, and work when secrets are in use,
# remove this too.
filter_secrets: false
matrix:
  allow_failures:
    - os: windows
env:
  - YARN_GPG=no
if: branch = master OR tag IS present
dist: xenial
addons:
  apt:
    packages:
      - libudev-dev
cache: yarn
install:
  - yarn install --network-timeout 1000000
script:
  - yarn run build:$TRAVIS_OS_NAME
after_script:
  - yarn add --dev aws-sdk
  - tools/s3-upload.js
