language: node_js
node_js:
  - 12

jobs:
  include:
    - os: linux
      dist: focal
    - os: linux
      dist: focal
      arch: arm64
    - os: osx
      osx_image: "xcode11.6"
    - os: windows

# This (filter_secrets) is generally unsafe, but we only run builds for master,
# so it is acceptable. If we remove the branch restriction, remove this too.
# If Windows builds on Travis are fixed, and work when secrets are in use,
# remove this too.
#
# See: https://travis-ci.community/t/current-known-issues-please-read-this-before-posting-a-new-topic/264
filter_secrets: false
env:
  - YARN_GPG=no
if: (branch = master OR tag IS present) OR (type != pull_request)
dist: xenial
addons:
  apt:
    packages:
      - libudev-dev
cache: yarn
before_install:
  - if [ "$TRAVIS_OS_NAME" = osx ]; then chmod +x tools/add-osx-cert.sh; fi
  - if [ "$TRAVIS_OS_NAME" = osx ]; then ./tools/add-osx-cert.sh; fi
install:
  - yarn install --network-timeout 1000000
script:
  - yarn run build:$TRAVIS_OS_NAME
after_script:
  - yarn add --dev aws-sdk
  - tools/s3-upload.js
